spring.application.name=auth-server
server.port=8900

spring.cloud.nacos.discovery.ip=127.0.0.1
spring.cloud.nacos.discovery.heart-beat-interval=10000
spring.cloud.nacos.discovery.heart-beat-timeout=60000
spring.cloud.nacos.discovery.ip-delete-timeout=120000

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/auth_server
spring.datasource.username=root
spring.datasource.password=QLBM2905
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=zymwppt@qq.com
spring.mail.password=pgwtlmrnczonbdei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.port=6377
spring.data.redis.host=127.0.0.1
spring.data.redis.database=3



spring.cloud.inetutils.preferred-networks=127.0.0.1
spring.cloud.inetutils.ignored-interfaces=.*

spring.rabbitmq.addresses=localhost:5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10