spring.application.name=my-gateway

server.port=8889

spring.cloud.nacos.config.import-check.enabled=false

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://127.0.0.1:8900/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.public-key-fetch-timeout=30000


spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.routes[0].id=auth-server
spring.cloud.gateway.routes[0].uri=http://127.0.0.1:8900
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=shopping-server
spring.cloud.gateway.routes[1].uri=lb://shopping-server
spring.cloud.gateway.routes[1].predicates[0]=Path=/shopping/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=agent-server
spring.cloud.gateway.routes[2].uri=lb://agent-server
spring.cloud.gateway.routes[2].predicates[0]=Path=/agent/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

#spring.cloud.gateway.routes[0].id=auth-server
#spring.cloud.gateway.routes[0].uri=http://127.0.0.1:8900
#spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
